### PR TITLE
Fix: Q1 demo notes

### PR DESCRIPTION
**Pull request by ahie**

### CODE REVIEW

**Comment by ahie** [comment]
Do not merge. Pending further changes.

**Comment by marharyta** [comment]
opps, did I approve too early? @ahie ?

**Comment by marharyta** [comment]
Sorry :)

**Comment by marharyta** [comment]
@ahie Can I re-review?

**Comment by marharyta** [comment]
Apr-15-2020 17-28-59
At least in Chrome it looks like the icons are sticking as you move in and out.

**Comment by marharyta** [comment]
@ahie it looks good now

**Comment by ahie** [comment]
Reopening to restart CI.

**Pull request merged**
