### PR TITLE
AHTI-168 | Implement displaying of routes on the Map

### PR DESCRIPTION
**Pull request by ahie**

### CODE REVIEW

**Comment by ahie** [comment]
Note: it takes a while to load up enough features for the single route to show up in the UI. Select ferries from the top menu to load it faster.

**Comment by marharyta** [comment]
@ahie looks good to me, any idea why the pipeline is crushing?

**Comment by marharyta** [comment]
> @ahie looks good to me, any idea why the pipeline is crushing?

@ahie  Looks like some modules are not picked up, just like last time the one that I had
This is a reoccuring problem, we might wanna start testing locally with docker build .

Failed to load plugin 'prettier' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-prettier'

**Comment by marharyta** [comment]
@ahie looks like I managed to narrow down the problem with this one, it fails in review: https://gitlab.com/City-of-Helsinki/KuVa/github-mirrors/ahti-ui/-/jobs/483165430
Does not look like anything to me, though

**Comment by marharyta** [comment]
> @ahie looks like I managed to narrow down the problem with this one, it fails in review: https://gitlab.com/City-of-Helsinki/KuVa/github-mirrors/ahti-ui/-/jobs/483165430
> Does not look like anything to me, though

aaand, here you can tell I am a huge fa of Westworld (if you get the reference)

**Comment by marharyta** [comment]
@ahie according to update from Rurik, "Hi, we noticed that same error this morning in another pipeline job. It is a bug in the pipeline. We are already fixing it. Sorry for the inconvenience."

**Comment by marharyta** [comment]
Happy to merge!

**Pull request merged**
